version: '3.0'
services:
  app:
    depends_on:
      - db
    build:
      context: .
    command: /app
    ports:
      - 3005:3000
      - 3030:3030
  db:
    restart: always
    image: postgres:latest
    environment:
      POSTGRES_DB: url-shortener
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/url-shortener
    volumes:
      - ./data/postgres:/var/lib/postgresql/data/url-shortener
    ports:
      - 5430:5430