postgres:
  login: "postgres"
  password: "postgres"
  host: "db"
  port: "5432"
  dbname: "postgres"
  sslMode: "disable"
httpServer:
  address: ":3000"
  timeout: 4s
  idleTimeout: 60s
grpcAddr: "0.0.0.0:3030"

